version: '3.1'

services:

  server:
    image: superserver
    networks:
      - net
    ports:
      - 8080:8080
    depends_on:
      - postgress
    restart: on-failure
    volumes:
      - data:/data

  postgress:
    image: mdillon/postgis:10-alpine
    networks:
      - net
    volumes:
      - /data/postress:/data
      - data:/data
    restart: on-failure

networks:
  net:

volumes:
  data:
